import numpy as np
truth_range_dict = {'main_deflector_parameters_theta_E':(0,4),
                    'main_deflector_parameters_gamma':(1,3),
                    'main_deflector_parameters_gamma1':(-0.2,0.2),
                    'main_deflector_parameters_gamma2':(-0.2,0.2),
                    'main_deflector_parameters_e1':(-0.6,0.6),
                    'main_deflector_parameters_e2':(-0.6,0.6),
                    'source_parameters_e1':(-0.6,0.6),
                    'source_parameters_e1':(-0.6,0.6),
                    'main_deflector_parameters_center_x':(-0.6,0.6),
                    'main_deflector_parameters_center_y':(-0.6,0.6),
                    'lens_light_parameters_R_sersic':(0,2.5),
                    'lens_light_parameters_mag_app':(12,25),
                    'main_deflector_parameters_z_lens':(0,2),
                    'source_parameters_z_source':(0,7),
                    'source_parameters_mag_app':(18,30),
                    'source_parameters_R_sersic':(0,2)
                   }

bin_dict = {'main_deflector_parameters_theta_E':np.arange(0,4.25,0.25),
                    'main_deflector_parameters_gamma':np.arange(1,3.25,0.25),
                    'main_deflector_parameters_gamma1':np.arange(-0.2,0.205,0.05),
                    'main_deflector_parameters_gamma2':np.arange(-0.2,0.205,0.05),
                    'main_deflector_parameters_e1':np.arange(-0.6,0.7,0.1),
                    'main_deflector_parameters_e2':np.arange(-0.6,0.7,0.1),
                    'source_parameters_e1':np.arange(-0.6,0.7,0.1),
                    'source_parameters_e2':np.arange(-0.6,0.7,0.1),
                    'main_deflector_parameters_center_x':np.arange(-0.2,0.205,0.05),
                    'main_deflector_parameters_center_y':np.arange(-0.2,0.205,0.05),
                    'lens_light_parameters_R_sersic':np.arange(0,2.6,0.1),
                    'lens_light_parameters_mag_app':np.arange(12,26,1),
                    'main_deflector_parameters_z_lens':np.arange(0,2.1,0.1),
                    'source_parameters_z_source':np.arange(0,7.5,0.5),
                    'source_parameters_mag_app':np.arange(18,31,1),
                    'source_parameters_R_sersic':np.arange(0,2.1,0.1)
                    }
title_dict = {
    'main_deflector_parameters_gamma':'Density Slope, $\gamma$',
    'main_deflector_parameters_theta_E':'Einstein radius, $\\theta_E$ (")',
    'main_deflector_parameters_e1':'Lens Ellipticity, $e_1$',
    'main_deflector_parameters_e2':'Lens Ellipticity, $e_2$',
    'main_deflector_parameters_gamma1':'Lens Shear,$\gamma_1$',
    'main_deflector_parameters_gamma2':'Lens Shear,$\gamma_2$',
    'main_deflector_parameters_center_x':'Lens Center, x (")',
    'main_deflector_parameters_center_y':'Lens Center, y (")',
    'lens_light_parameters_mag_app':'$mag_i$ (Lens)',
    'source_parameters_mag_app':'$mag_i$ (Source)',
    'main_deflector_parameters_z_lens':'$z_L$',
    'source_parameters_z_source':'$z_S$',
    'lens_light_parameters_R_sersic':'Lens Light: $R_{eff}$ (")',
    'source_parameters_R_sersic':'Source Light: $R_{eff}$ (")',
    'source_parameters_e1':'Source Ellipticity, $e_1$',
    'lens-source_separation':'Lens-Source Separation',
    'Magnification':'Magnification',
    'lens_light_parameters_center_x':'Lens Light Center, x (")',
    'lens_light_parameters_center_y':'Lens Light Center, y (")',
    'lens_light_parameters_e1':'Lens Light Ellipticity, $e_1$',
    'lens_light_parameters_e2':'Lens Light Ellipticity, $e_2$',
    'lens_light_parameters_z_source':'$z_L$ (Light)',
    'source_parameters_center_x':'Source Center, x (")',
    'source_parameters_center_y':'Source Center, y (")',
    'source_parameters_e1':'Source Ellipticity, $e_1$',
    'source_parameters_e2':'Source Ellipticity, $e_2$'
}

title_dict_short = {
    'main_deflector_parameters_gamma':'$\gamma_{L}$',
    'main_deflector_parameters_theta_E':'$\\theta_E$ (")',
    'main_deflector_parameters_e1':'$e_{1,L}$',
    'main_deflector_parameters_e2':'$e_{2,L}$',
    'main_deflector_parameters_gamma1':'$\gamma_1$',
    'main_deflector_parameters_gamma2':'$\gamma_2$',
    'main_deflector_parameters_center_x':'$x_{L}$ (")',
    'main_deflector_parameters_center_y':'$y_{L}$ (")',
    'lens_light_parameters_mag_app':'$m_{i,L}$',
    'source_parameters_mag_app':'$m_{i,S}$',
    'main_deflector_parameters_z_lens':'$z_L$',
    'source_parameters_z_source':'$z_S$',
    'lens_light_parameters_R_sersic':'$R_{eff,L}$ (")',
    'source_parameters_R_sersic':'$R_{eff,S}$ (")',
    'source_parameters_e1':'$e_{1,S}$',
    'lens-source_separation':'Lens-Source Separation',
    'Magnification':'$\mu$'
}

units_dict = {
    'main_deflector_parameters_gamma':'',
    'main_deflector_parameters_theta_E':'(")',
    'main_deflector_parameters_e1':'',
    'main_deflector_parameters_e2':'',
    'main_deflector_parameters_gamma1':'',
    'main_deflector_parameters_gamma2':'',
    'main_deflector_parameters_center_x':'(")',
    'main_deflector_parameters_center_y':'(")',
    'lens_light_parameters_mag_app':'',
    'source_parameters_mag_app':'',
    'main_deflector_parameters_z_lens':'',
    'source_parameters_z_source':'',
    'lens_light_parameters_R_sersic':'(")',
    'source_parameters_R_sersic':'(")',
    'source_parameters_e1':'',
    'lens-source_separation':'(")',
    'Magnification':''
}

Error_range_dict = {'main_deflector_parameters_theta_E':(-0.4,0.4),
                    'main_deflector_parameters_gamma':(-0.4,0.4),
                    'main_deflector_parameters_gamma1':(-0.2,0.2),
                    'main_deflector_parameters_gamma2':(-0.2,0.2),
                    'main_deflector_parameters_e1':(-0.4,0.4),
                    'main_deflector_parameters_e2':(-0.4,0.4),
                    'main_deflector_parameters_center_x':(-0.2,0.2),
                    'main_deflector_parameters_center_y':(-0.2,0.2),
                    'lens_light_parameters_R_sersic':(-0.2,0.2),
                    'lens_light_parameters_mag_app':(-1,1)
                   }